import {Geist, Geist_Mono} from "next/font/google";
import "@/styles/global.css";
import {I18nProvider} from "@/contexts/i18n";
import Cookies from "js-cookie";
import {Metadata} from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  // Lấy locale từ cookie
  const locale = Cookies.get("locale") || "en";  // Mặc định là tiếng Anh nếu không có cookie

  return (
    <html lang={locale}>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <I18nProvider>{children}</I18nProvider>
    </body>
    </html>
  );
}
